# Generated by Django 3.2.5 on 2021-07-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0006_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='MEDIA_COMPANY_IMAGE_DIR/bnr-1.png', height_field='height_field', upload_to='MEDIA_COMPANY_IMAGE_DIR', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.ImageField(height_field='height_field', upload_to='MEDIA_SPECIALITY_IMAGE_DIR', width_field='width_field'),
        ),
    ]
