# Generated by Django 3.2.5 on 2021-07-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0007_auto_20210726_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(height_field='height_field', upload_to='company_images', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.ImageField(height_field='height_field', upload_to='speciality_images', width_field='width_field'),
        ),
    ]
