# Generated by Django 3.2.5 on 2021-07-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0009_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='100x60', height_field='height_field', upload_to='company_images', width_field='width_field'),
        ),
    ]
