# Generated by Django 3.2.5 on 2021-07-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0010_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.ImageField(default='100x60', height_field='height_field', upload_to='speciality_images', width_field='width_field'),
        ),
    ]
