# Generated by Django 3.2.5 on 2021-08-10 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Job', '0014_alter_application_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, "I'm not looking for a job"), (2, "I'm looking for a job"), (3, 'I am currently sifting through offers')])),
                ('salary', models.IntegerField()),
                ('grade', models.PositiveSmallIntegerField(choices=[(1, 'Trainee'), (2, 'Junior'), (3, 'Middle'), (4, 'Senior '), (5, 'Lid')])),
                ('education', models.CharField(max_length=100)),
                ('experience', models.TextField()),
                ('portfolio', models.TextField()),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='Job.specialty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
